version: "3.9"
services:
  backend-contoh:
    image: giovana02/cilist-backend:latest
    ports:
      - 5000:5000
    environment:
      DATABASE_USERNAME: "people"
      DATABASE_PASSWORD: "people123"
      DATABASE_DATABASE: "people" 
      DATABASE_HOST: "awsss.com"
      DATABASE_PORT: 3306
      BASE_URL_PORT: 5000
